require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.3
  Exclude:
    - 'bin/**/**'
    - 'vendor/**/**'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/HashSyntax:
  EnforcedShorthandSyntax: 'never'

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/SymbolArray:
  EnforcedStyle: "brackets"

Style/WordArray:
  EnforcedStyle: "brackets"

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Max: 15

RSpec/ImplicitSubject:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/AbcSize:
  Max: 20
