require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'config/**/**'
    - 'bin/**/**'
    - 'lib/**/**'
    - 'vendor/**/**'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'db/schema.rb'

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/NestedGroups:
  Max: 3

Style/HashSyntax:
  EnforcedShorthandSyntax: 'never'

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Max: 15

RSpec/ImplicitSubject:
  Enabled: false
