name: Lint, Audit and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUBY_VERSION: 3.1.3

jobs:
  lint_and_audit:
    name: Lint and Audit
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{env.RUBY_VERSION}}
          bundler-cache: true

      - name: Run Zeitwerk check
        run: bundle exec rails zeitwerk:check

      - name: Run Bundler check and audit
        run: bundle exec bundle-audit check --update

      - name: Run Brakeman
        run: bundle exec brakeman

      - name: Run Rubocop
        run: bundle exec rubocop

  test:
    needs: lint_and_audit
    name: Test
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:15.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{env.RUBY_VERSION}}
          bundler-cache: true

      - name: Prepare ENV
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432
        run: |
          bundle exec rails db:test:prepare
      - name: Run RSpec
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432
        run: bundle exec rspec
